personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[projects."/home/greenhead/Workspace/zaritalk-front"]
trust_level = "trusted"

[features]
multi_agent = true
apps = true
prevent_idle_sleep = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--browser-url=http://127.0.0.1:9222", "--no-usage-statistics"]
