personality = "pragmatic"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[projects."/home/greenhead/IdeaProjects/zaritalk-front"]
trust_level = "trusted"
